envs:
- GITHUB_ACCESS_TOKEN: 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
  opts:
    is_expand: false
- GOOGLE_APPLICATION_CREDENTIALS: "/Users/indrajitroy/smallcase/scGitHub/gw-mob-android/service_account.json"
  opts:
    is_expand: false
- AWS_ACCESS_KEY_ID: AKIA2W5NWF6VPWNFZLE5
  opts:
    is_expand: false
- AWS_SECRET_ACCESS_KEY: po3YSIpWzd2JkCbuhmvINn2jIaETYpSjwAF2A0ui
  opts:
    is_expand: false
- COCOAPODS_TRUNK_TOKEN: ccc331192395692b04061391b6122fae
  opts:
    is_expand: false
- FIREBASE_APP_ID: "1:615764606669:ios:1d34e3a1320eae16e7b384"
  opts:
    is_expand: false