name: 'Update Podspec version and source'
description: 'A reusable step that can be called with different inputs'
inputs:
  version:
    description: 'Version'
    required: true
  versionCode:
    description: 'Version Code'
    required: true
  scheme:
    description: 'Scheme'
    required: false
  remix:
    description: 'Remix'
    required: false
  remixBucket:
    description: 'Remix Bucket'
    required: false
  podspec:
    description: 'Podspec path'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Script with Input
      shell: bash
      run: |
        podspec="${{ inputs.podspec }}"
        cat $podspec

        new_version="${{ inputs.version }}"

        source=$(jq -r '.source.http' "$podspec")
        updated_source=$(echo $source | sed -E "s|(/[^/]+/)[^/]+(/[^/]+$)|\1${new_version}\2|")
        jq --arg new_version "$new_version" --arg new_source "$updated_source" '.version = $new_version | .source.http = $new_source' "$podspec" > tmp.$$.json && mv tmp.$$.json "$podspec"

        if [[ "${{ inputs.versionCode }}" != "" ]];then
          new_version="$new_version-${{ inputs.versionCode }}"
        fi

        scheme="${{ inputs.scheme }}"
        if [[ "$scheme" != "release" ]];then
          new_version="$new_version-$scheme"
        fi
        
        remix="${{ inputs.remix }}"
        remixBucket="${{ inputs.remixBucket }}"

        if [[ "${{ inputs.remix }}" != "" ]];then
          podRoot=$(echo "$podspec" | awk -F'/' '{print $1}')
          podspec_name=$(basename "$podspec" | awk -F'.' '{print $1}')
          new_podspec_name="$podspec_name-$remix"
          remixPodspec="$podRoot/podspecs/$scheme/$new_podspec_name.podspec.json"

          base_url=$(echo "$source" | awk -F'/' '{print $1 "//" $3}')
          framework_name=$(echo "$source" | awk -F'/' '{print $NF}')
          new_source="$base_url/$remixBucket/$remix/$new_version/$framework_name"

          jq --arg new_name "$new_podspec_name" --arg new_version "$new_version" --arg new_source "$new_source" '.name = $new_name | .version = $new_version | .source.http = $new_source' "$podspec" > "$remixPodspec"
          cat $remixPodspec
        fi
        cat $podspec
