name: Create Release

on:
  workflow_dispatch:
    inputs:
      main_version:
        description: 'Main repository release version'
        required: true
        type: string
      smallcase_gateway_version:
        description: 'SCGateway release version (optional)'
        required: false
        type: string
      loans_version:
        description: 'SCLoans release version (optional)'
        required: false
        type: string

jobs:
  create-main-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: feat/ci
        fetch-depth: 0

    - name: Create and push release branch
      run: |
        git branch | cat
        git log --max-count=5 "--pretty=format:%H%n%an%n%ad%n%B" | cat
        RELEASE_BRANCH=release/${{ github.event.inputs.main_version }}
        git checkout -b ${RELEASE_BRANCH}
        
        git branch | cat
        git log --max-count=5 "--pretty=format:%H%n%an%n%ad%n%B" | cat
        git push origin ${RELEASE_BRANCH}

    - name: Create Pull Request
      id: create_pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --base dev --head release/${{ github.event.inputs.main_version }} --title "Release/${{ github.event.inputs.main_version }}" --body "" --label "release"

  create-smallcase-gateway-release:
    needs: create-main-release
    if: ${{ github.event.inputs.smallcase_gateway_version }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout smallcase_gateway repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/gw-mob-sdk-ios
        ref: dev
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Create and push release branch for smallcase_gateway
      run: |
        git branch | cat
        git log --max-count=5 "--pretty=format:%H%n%an%n%ad%n%B" | cat
        VERSION=${{ github.event.inputs.smallcase_gateway_version }}
        git checkout -b release/${VERSION}

        git branch | cat
        git log --max-count=5 "--pretty=format:%H%n%an%n%ad%n%B" | cat
        git push origin release/${VERSION}

    - name: Create Pull Request for smallcase_gateway
      id: create_pr_smallcase_gateway
      env:
        GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        gh pr create --base prod --head release/${{ github.event.inputs.main_version }} --title "Release/${{ github.event.inputs.main_version }}" --body "" --label "release"

  create-loans-release:
    needs: create-main-release
    if: ${{ github.event.inputs.loans_version }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout loans repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/gw-mob-sdk-las-ios
        ref: master
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Create and push release branch for loans
      run: |
        git branch | cat
        git log --max-count=5 "--pretty=format:%H%n%an%n%ad%n%B" | cat
        VERSION=${{ github.event.inputs.loans_version }}
        git checkout -b release/${VERSION}
        git push origin release/${VERSION}

    - name: Create Pull Request for loans
      id: create_pr_loans
      env:
        GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        gh pr create --base prod --head release/${{ github.event.inputs.main_version }} --title "Release/${{ github.event.inputs.main_version }}" --body "" --label "release"
