name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Create and push release branch
      run: |
        git branch | cat
        git log --max-count=5 "--pretty=format:%H%n%an%n%ad%n%B" | cat
        RELEASE_BRANCH=release/${{ github.event.inputs.version }}
        git checkout -b ${RELEASE_BRANCH}
        
        git branch | cat
        git log --max-count=5 "--pretty=format:%H%n%an%n%ad%n%B" | cat
        git push origin ${RELEASE_BRANCH}

    - name: Create Pull Request
      id: create_pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --base dev --head release/${{ github.event.inputs.version }} --title "Release/${{ github.event.inputs.version }}" --body "" --label "release"