name: Create Release

on:
  workflow_dispatch:
    inputs:
      scgVersion:
        description: 'Scg version'
        required: true
        type: string
      loansVersion:
        description: 'Loans version'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Create and push release branch
      id: create_branch
      run: |
        git branch | cat
        git log --max-count=5 "--pretty=format:%H%n%an%n%ad%n%B" | cat
        
        scg="scg-v${{ inputs.scgVersion }}"
        loans="loans-v${{ inputs.loansVersion }}"
        
        RELEASE_BRANCH="release/"
        release_version=""
        if [[ -n "$scg" && -n "$loans" ]]; then
          release_version="${scg}_${loans}"
          RELEASE_BRANCH+="$release_version"
        else
          release_version="${scg}${loans}"
          RELEASE_BRANCH+="$release_version"
        fi
        
        echo "::set-output name=release_branch::$RELEASE_BRANCH"
        echo "::set-output name=release_version::$release_version"
        
        git checkout -b ${RELEASE_BRANCH}
        
        git branch | cat
        git log --max-count=5 "--pretty=format:%H%n%an%n%ad%n%B" | cat
        git push origin ${RELEASE_BRANCH}

    - name: Create Pull Request
      id: create_pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        branch="${{ steps.create_branch.outputs.release_branch }}"
        release_version="${{ steps.create_branch.outputs.release_version }}"
        gh pr create --base prod --head "$branch" --title "Release/$release_version" --body "" --label "release"