name: Bump Version

on:
  workflow_dispatch:
    inputs:
      scliVersion:
        description: "scli version"
        required: true
        default: "v0.0.4-26-g47943f3"
      releaseType:
        type: choice
        description: "Release type"
        options:
          - qa
          - internal
          - prod
      bumpType:
        type: choice
        description: "Version bump type"
        options:
          - patch
          - minor
          - major
          - auto
      scg:
        description: "Should bump scg?"
        required: true
        type: boolean
      loans:
        description: "Should bump loans?"
        required: true
        type: boolean
      bitrise:
        description: "Trigger bitrise?"
        type: boolean
        default: false

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git configuration
        run: |
          git config --global user.name "Github Action Bot"
          git config --global user.email "gatewaytech@smallcase.com"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install scli
        uses: ./.github/actions/install-scli
        with:
          token: "${{ secrets.GH_ACCESS_TOKEN }}"
          version: "${{ github.event.inputs.scliVersion }}"

      - name: Bump scg
        if: ${{ inputs.scg }}
        id: bump-scg
        run: |
          if [ "${{ github.event.inputs.releaseType }}" == "prod" ];then
            scli versionBump smallcase_gateway/SCGateway/Helpers/Info.plist --bumpType "${{ github.event.inputs.bumpType }}" --vkey "CFBundleShortVersionString" --vckey "CFBundleVersion"
          else
            scli versionBump smallcase_gateway/SCGateway/Helpers/Info.plist --onlyCode --vckey "CFBundleVersion"
          fi
      - name: Bump loans
        if: ${{ inputs.loans }}
        id: bump-loans
        run: |
          if [ "${{ github.event.inputs.releaseType }}" == "prod" ];then
            scli versionBump loans/Loans/Info.plist --bumpType "${{ github.event.inputs.bumpType }}" --vkey "CFBundleShortVersionString" --vckey "CFBundleVersion"
          else
            scli versionBump loans/Loans/Info.plist --onlyCode --vckey "CFBundleVersion"
          fi    
      - name: Bump smart investing
        id: bump-si
        run: |
          if [ "${{ github.event.inputs.releaseType }}" == "prod" ];then
            scli versionBump SmartInvesting/Info.plist --bumpType "${{ github.event.inputs.bumpType }}" --vkey "CFBundleShortVersionString" --vckey "CFBundleVersion"
          else
            scli versionBump SmartInvesting/Info.plist --onlyCode --vckey "CFBundleVersion"
          fi

      - name: Set Versions
        id: set-versions
        run: |
          si_version=$(scli prop SmartInvesting/Info.plist "CFBundleShortVersionString")
          si_version_code=$(scli prop SmartInvesting/Info.plist "CFBundleVersion")

          echo "::set-output name=si_version::$si_version"
          echo "::set-output name=si_version_code::$si_version_code"

          scg_version=$(scli prop smallcase_gateway/SCGateway/Helpers/Info.plist "CFBundleShortVersionString")
          scg_version_code=$(scli prop smallcase_gateway/SCGateway/Helpers/Info.plist "CFBundleVersion")

          echo "::set-output name=scg_version::$scg_version"
          echo "::set-output name=scg_version_code::$scg_version_code"
          
          loans_version=$(scli prop loans/Loans/Info.plist "CFBundleShortVersionString")
          loans_version_code=$(scli prop loans/Loans/Info.plist "CFBundleVersion")
          
          echo "::set-output name=loans_version::$loans_version"
          echo "::set-output name=loans_version_code::$loans_version_code"
      - name: Outputs
        run: |
          echo ${{ steps.set-versions.outputs.scg_version }}
          echo ${{ steps.set-versions.outputs.scg_version_code }}

          echo ${{ steps.set-versions.outputs.loans_version }}
          echo ${{ steps.set-versions.outputs.loans_version_code }}

          echo ${{ steps.set-versions.outputs.si_version }}
          echo ${{ steps.set-versions.outputs.si_version_code }}

      - name: Update SCG Podspec
        if: ${{ inputs.scg }}
        uses: ./.github/actions/update-podspec
        with:
          version: "${{ steps.set-versions.outputs.scg_version }}"
          versionCode: "${{ github.event.inputs.releaseType != 'prod' && steps.set-versions.outputs.scg_version_code || '' }}"
          podspec: "smallcase_gateway/internal/SCGateway-ci.podspec.json"
      - name: Update Loans Podspec
        if: ${{ inputs.loans }}
        uses: ./.github/actions/update-podspec
        with:
          version: "${{ steps.set-versions.outputs.loans_version }}"
          versionCode: "${{ github.event.inputs.releaseType != 'prod' && steps.set-versions.outputs.loans_version_code || '' }}"
          podspec: "loans/internal/SCLoans-ci.podspec.json"

      - name: Commit
        run: |
          commit_type="chore(${{ github.event.inputs.releaseType }}):"
          si="si:${{ steps.set-versions.outputs.si_version }}-${{ steps.set-versions.outputs.si_version_code }}"
          scg="scg:${{ steps.set-versions.outputs.scg_version }}-${{ steps.set-versions.outputs.scg_version_code }}"
          loans="loans:${{ steps.set-versions.outputs.loans_version }}-${{ steps.set-versions.outputs.loans_version_code }}"

          commit_msg=""
          commit_desc="$scg, $loans, $si"

          if [[ "${{ inputs.scg }}" == "true" && "${{ inputs.loans }}" == "true" ]];then
            commit_msg="$commit_type $scg $loans"
          elif [[ "${{ inputs.scg }}" == true ]];then
            commit_msg="$commit_type $scg"
          elif [[ "${{ inputs.loans }}" == "true" ]];then
            commit_msg="$commit_type $loans"
          else
            commit_msg="$commit_type $si"
          fi

          git add .
          git status
          git commit -m "$commit_msg" -m "$commit_desc"

      - name: Push
        run: |
          git push
      
      - name: Trigger Bitrise Workflow
        if: ${{ inputs.bitrise }}
        run: |
          BITRISE_APP_SLUG="d6c77e34-9075-4262-8c39-12b4d5adf82c"

          WORKFLOW_ID="release-qa"
          if [[ "${{ inputs.releaseType }}" == "prod" ]];then
            WORKFLOW_ID="release-prod"
          fi
          if [[ "${{ inputs.releaseType }}" == "internal" ]];then
            WORKFLOW_ID="release-internal"
          fi

          scli triggerBitrise --appSlug "$BITRISE_APP_SLUG" --workflowId "${WORKFLOW_ID}" --branch "${{ github.head_ref || github.ref_name }}" \
          --bitriseToken "${{ secrets.BITRISE_API_TOKEN }}" \
          --message "$(git log -1 --pretty=%B%n%H)"
