name: Bump Version

on:
  workflow_dispatch:
    inputs:
      remix:
        description: "The remix name of the SDK"
        default: "internal"
      scheme:
        type: choice
        description: "Scheme"
        required: true
        options:
          - release
          - debug
      bumpType:
        type: choice
        description: "Version bump type"
        options:
          - onlyCode
          - patch
          - minor
          - major
          - auto
      scg:
        description: "SCGateway"
        type: boolean
        default: false
      scgRemixBucket:
        type: choice
        description: "SCG internal bucket"
        options:
          - scgateway_internal
          - laons_internal
      loans:
        description: "SCLoans"
        type: boolean
        default: false
      loansRemixBucket:
        type: choice
        description: "Loans internal bucket"
        options:
          - loans_internal
          - laons_internal
      bitriseWorkflow:
        type: choice
        description: "Bitrise Workflow"
        required: true
        options:
          - none
          - release-app
          - release-sdks
      scliVersion:
        description: "scli version"
        default: "v0.2.0"

env:
  SCG_INFO_PLIST: smallcase_gateway/SCGateway/Helpers/Info.plist
  LOANS_INFO_PLIST: loans/Loans/Info.plist
  SI_INFO_PLIST: SmartInvesting/Info.plist
  VERSION_KEY: CFBundleShortVersionString
  VERSION_CODE_KEY: CFBundleVersion
jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git configuration
        run: |
          git config --global user.name "Github Action Bot"
          git config --global user.email "gatewaytech@smallcase.com"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install scli
        uses: ./.github/actions/install-scli
        with:
          token: "${{ secrets.GH_ACCESS_TOKEN }}"
          version: "${{ github.event.inputs.scliVersion }}"

      - name: Bump scg
        if: ${{ inputs.scg }}
        id: bump-scg
        run: |
          if [[ "${{ github.event.inputs.bumpType }}" != "onlyCode" ]];then
            scli versionBump "$SCG_INFO_PLIST" --bumpType "${{ github.event.inputs.bumpType }}" --vkey "$VERSION_KEY" --vckey "$VERSION_CODE_KEY"
          else
            scli versionBump "$SCG_INFO_PLIST" --onlyCode --vckey "$VERSION_CODE_KEY"
          fi
      - name: Bump loans
        if: ${{ inputs.loans }}
        id: bump-loans
        run: |
          if [[ "${{ github.event.inputs.bumpType }}" != "onlyCode" ]];then
            scli versionBump "$LOANS_INFO_PLIST" --bumpType "${{ github.event.inputs.bumpType }}" --vkey "$VERSION_KEY" --vckey "$VERSION_CODE_KEY"
          else
            scli versionBump "$LOANS_INFO_PLIST" --onlyCode --vckey "$VERSION_CODE_KEY"
          fi    
      - name: Bump smart investing
        id: bump-si
        run: |
          if [[ "${{ github.event.inputs.bumpType }}" != "onlyCode" ]];then
            scli versionBump "$SI_INFO_PLIST" --bumpType "${{ github.event.inputs.bumpType }}" --vkey "$VERSION_KEY" --vckey "$VERSION_CODE_KEY"
          else
            scli versionBump "$SI_INFO_PLIST" --onlyCode --vckey "$VERSION_CODE_KEY"
          fi

      - name: Set Versions
        id: set-versions
        run: |
          si_version=$(scli prop $SI_INFO_PLIST "$VERSION_KEY")
          si_version_code=$(scli prop $SI_INFO_PLIST "$VERSION_CODE_KEY")

          echo "::set-output name=si_version::$si_version"
          echo "::set-output name=si_version_code::$si_version_code"

          scg_version=$(scli prop $SCG_INFO_PLIST "$VERSION_KEY")
          scg_version_code=$(scli prop $SCG_INFO_PLIST "$VERSION_CODE_KEY")

          echo "::set-output name=scg_version::$scg_version"
          echo "::set-output name=scg_version_code::$scg_version_code"
          
          loans_version=$(scli prop $LOANS_INFO_PLIST "$VERSION_KEY")
          loans_version_code=$(scli prop $LOANS_INFO_PLIST "$VERSION_CODE_KEY")
          
          echo "::set-output name=loans_version::$loans_version"
          echo "::set-output name=loans_version_code::$loans_version_code"

      - name: Outputs
        run: |
          echo ${{ steps.set-versions.outputs.scg_version }}
          echo ${{ steps.set-versions.outputs.scg_version_code }}

          echo ${{ steps.set-versions.outputs.loans_version }}
          echo ${{ steps.set-versions.outputs.loans_version_code }}

          echo ${{ steps.set-versions.outputs.si_version }}
          echo ${{ steps.set-versions.outputs.si_version_code }}
          
      - name: Update SCG Podspec
        if: ${{ inputs.scg }}
        uses: ./.github/actions/update-podspec
        with:
          version: "${{ steps.set-versions.outputs.scg_version }}"
          versionCode: "${{ steps.set-versions.outputs.scg_version_code }}"
          remix: "${{ github.event.inputs.remix }}"
          scheme: "${{ github.event.inputs.scheme }}"
          remixBucket: "${{ github.event.inputs.scgRemixBucket }}"
          podspec: "${{ vars.SCG_PODSPEC }}"
      - name: Update Loans Podspec
        if: ${{ inputs.loans }}
        uses: ./.github/actions/update-podspec
        with:
          version: "${{ steps.set-versions.outputs.loans_version }}"
          versionCode: "${{ steps.set-versions.outputs.loans_version_code }}"
          remix: "${{ github.event.inputs.remix }}"
          scheme: "${{ github.event.inputs.scheme }}"
          remixBucket: "${{ github.event.inputs.loansRemixBucket }}"
          podspec: "${{ vars.LOANS_PODSPEC }}"

      - name: Commit, Tag & Push
        uses: ./.github/actions/commit-tag-push
        with:
          siVersion: "${{ steps.set-versions.outputs.si_version }}"
          siVersionCode: "${{ steps.set-versions.outputs.si_version_code }}"
          scg: ${{ inputs.scg }}
          scgVersion: "${{ steps.set-versions.outputs.scg_version }}"
          scgVersionCode: "${{ steps.set-versions.outputs.scg_version_code }}"
          loans: ${{ inputs.loans }}
          loansVersion: "${{ steps.set-versions.outputs.loans_version }}"
          loansVersionCode: "${{ steps.set-versions.outputs.loans_version_code }}"
          remix: "${{ inputs.remix }}"
          tag: "${{ inputs.bitriseWorkflow == 'release-sdks' }}"

      - name: Trigger Bitrise Workflow
        if: ${{ inputs.bitriseWorkflow != 'none' }}
        run: |
          WORKFLOW_ID="${{ inputs.bitriseWorkflow }}"
          
          release_scg="${{ inputs.scg }}"
          scg_podspec="smallcase_gateway/podspecs/${{ github.event.inputs.scheme }}/SCGateway-${{ github.event.inputs.remix }}.podspec.json"
          release_loans="${{ inputs.loans }}"
          loans_podspec="loans/podspecs/${{ github.event.inputs.scheme }}/SCLoans-${{ github.event.inputs.remix }}.podspec.json"

          envs="OVERRIDE_RELEASE_SCG=$release_scg,\
          OVERRIDE_SCG_PODSPEC=$scg_podspec,\
          OVERRIDE_BITRISE_SCHEME=${{ inputs.scheme }},\
          OVERRIDE_RELEASE_LOANS=$release_loans,\
          OVERRIDE_LOANS_PODSPEC=$loans_podspec"

          scli triggerBitrise --appSlug "${{ vars.BITRISE_APP_SLUG }}" --workflowId "$WORKFLOW_ID" --branch "${{ github.head_ref || github.ref_name }}" \
          --bitriseToken "${{ secrets.BITRISE_API_TOKEN }}" \
          --envs "$envs" \
          --message "$(git log -1 --pretty=%B%n%H)"
